CC=mpic++

#FLAGS=-std=c++0x

all: khammingDiference2H2-P

khammingDiference2H2-P: khammingDiference2H2-P.cpp
	$(CC) $(FLAGS) khammingDiference2H2-P.cpp -o khammingDiference2H2-P	

clean:
	rm khammingDiference2H2-P