CC=g++

FLAGS=-std=c++0x

all: khammingDiference2H1 khammingDiference2H2

khammingDiference2H1: khammingDiference2H1.cpp
	$(CC) $(FLAGS) khammingDiference2H1.cpp -o khammingDiference2H1

khammingDiference2H2: khammingDiference2H2.cpp
	$(CC) $(FLAGS) khammingDiference2H2.cpp -o khammingDiference2H2	

clean:
	rm khammingDiference2H1
	rm khammingDiference2H2
