CC=g++

FLAGS=-std=c++0x

all: khammingDiference2 khammingDiference1

khammingDiference2: khammingDiference2.cpp
	$(CC) $(FLAGS) khammingDiference2.cpp -o khammingDiference2

khammingDiference1: khammingDiference1.cpp
	$(CC) $(FLAGS) khammingDiference1.cpp -o khammingDiference1	

clean:
	rm khammingDiference2
	rm khammingDiference1
